### ISSUE TITLE
No demo on website

### ISSUE THREAD

**Issue by JuhQ** [jonahvsweb/touchpoint-js#4]
http://jonahvsweb.github.io/touchpoint-js/ is missing the demo.
Github readme has a link to http://jonahvsweb.com/in-the-lab/lib/touchpoint-js/demo.html, this should be added to the website as well.

**Comment by jonahvsweb** [comment]
Thanks @JuhQ, I realize that the site isn't very robust and should definitely have the demo amongst other things. I have plans to update the site this week, but wanted to just get a Github pages placeholder up, more because I never actually used GH pages before. 

That said, per your suggestion, I'll add a link to the demo for the time being. Thanks for the input!
